### ISSUE TITLE
ADB not generating public keys

### ISSUE THREAD

**Issue by carolinadp** [Isaac95Mendez/UP-Android-Automation-Framework#54]
Newer versions of ADB are not generaring the file adbkey.pub for the public keys, making only the private key. This makes it difficult for ADB to access remote devices through STF. 

This is expected behavior on ADB's part, as indicated in this commit https://github.com/aosp-mirror/platform_system_core/commit/2dc4cabe0639c71014d729dd92eff19289429c89 

There exist methods for generating public keys given the private keys, as mentioned here: https://security.stackexchange.com/questions/172274/can-i-get-a-public-key-from-an-rsa-private-key. However, some android specific code will be needed, as the default RSA pubkey format is not compatible with ADB.

**Comment by carolinadp** [comment]
A workaround that I managed to do was to install the previous version of ADB, which seems to be the last one that doesn't have this problem. This version is available to download from https://dl.google.com/android/repository/platform-tools_r28.0.1-windows.zip but in the future it would be ideal to find some way to generate the correct public key, more so if this will be open to the public.

**Comment by carolinadp** [comment]
Seems that this issue has been reported in the OpenSTF github https://github.com/openstf/stf/issues/1030 there seems to be a workaround for any ADB version. I will try it later and see if it works.

**Comment by Isaac95Mendez** [comment]
Solved in a future version
